server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true